package com.sodi.metareports.metaaccount;
import com.sodi.metareports.audit.AuditService; import java.text.Normalizer; import java.util.*; import org.springframework.dao.DataIntegrityViolationException; import org.springframework.jdbc.core.JdbcTemplate; import org.springframework.stereotype.Service; import org.springframework.transaction.annotation.Transactional;
@Service public class AssetService { private final JdbcTemplate jdbc; private final AuditService audit; public AssetService(JdbcTemplate j,AuditService a){jdbc=j;audit=a;}
 public long count(){return jdbc.queryForObject("select (select count(*) from facebook_page)+(select count(*) from instagram_account)+(select count(*) from meta_ad_account)",Long.class);}
 public List<Map<String,Object>> all(){return jdbc.queryForList("select 'FACEBOOK' type,id,meta_page_id meta_id,page_name name,active from facebook_page union all select 'INSTAGRAM',id,meta_instagram_account_id,coalesce(username,display_name),active from instagram_account union all select 'AD_ACCOUNT',id,meta_ad_account_id,account_name,active from meta_ad_account order by type,name");}
 public List<Map<String,Object>> forClient(UUID id){return jdbc.queryForList("select 'FACEBOOK' type,fp.id,fp.meta_page_id meta_id,fp.page_name name from client_facebook_page x join facebook_page fp on fp.id=x.facebook_page_id where x.client_id=? and x.active_until is null union all select 'INSTAGRAM',ia.id,ia.meta_instagram_account_id,coalesce(ia.username,ia.display_name) from client_instagram_account x join instagram_account ia on ia.id=x.instagram_account_id where x.client_id=? and x.active_until is null union all select 'AD_ACCOUNT',aa.id,aa.meta_ad_account_id,aa.account_name from client_ad_account x join meta_ad_account aa on aa.id=x.ad_account_id where x.client_id=? and x.active_until is null",id,id,id);}
 public List<Map<String,Object>> prefixes(UUID id){return jdbc.queryForList("select id,prefix,description,primary_prefix from campaign_prefix where client_id=? and active order by primary_prefix desc,prefix",id);}
 @Transactional public void addFacebook(UUID client,String metaId,String name){requireId(metaId);UUID id=UUID.randomUUID();try{jdbc.update("insert into facebook_page(id,meta_page_id,page_name,normalized_page_name) values(?,?,?,?)",id,metaId.trim(),name.trim(),normalize(name));jdbc.update("insert into client_facebook_page(client_id,facebook_page_id) values(?,?)",client,id);}catch(DataIntegrityViolationException e){throw new DataIntegrityViolationException("Facebook Page ID already exists or is assigned",e);}audit.record("ASSET_ASSOCIATE","FacebookPage",id.toString(),"Facebook page associated",null,Map.of("metaId",metaId));}
 @Transactional public void addInstagram(UUID client,String metaId,String username){requireId(metaId);UUID id=UUID.randomUUID();try{jdbc.update("insert into instagram_account(id,meta_instagram_account_id,username,display_name) values(?,?,?,?)",id,metaId.trim(),username.trim(),username.trim());jdbc.update("insert into client_instagram_account(client_id,instagram_account_id) values(?,?)",client,id);}catch(DataIntegrityViolationException e){throw new DataIntegrityViolationException("Instagram Account ID already exists or is assigned",e);}audit.record("ASSET_ASSOCIATE","InstagramAccount",id.toString(),"Instagram account associated",null,Map.of("metaId",metaId));}
 @Transactional public void addAdAccount(UUID client,String metaId,String name,String currency,boolean exclusive){String canonical=metaId==null?null:metaId.trim().replaceFirst("(?i)^act_","");requireId(canonical);UUID id=UUID.randomUUID();try{jdbc.update("insert into meta_ad_account(id,meta_ad_account_id,account_name,account_currency,timezone_name,exclusive_client_account) values(?,?,?,?,?,?)",id,canonical,name.trim(),currency.trim().toUpperCase(),"America/Guatemala",exclusive);jdbc.update("insert into client_ad_account(client_id,ad_account_id,exclusive) values(?,?,?)",client,id,exclusive);}catch(DataIntegrityViolationException e){throw new DataIntegrityViolationException("Ad Account ID already exists or is incompatible",e);}audit.record("ASSET_ASSOCIATE","MetaAdAccount",id.toString(),"Ad account associated",null,Map.of("metaId",canonical,"exclusive",exclusive));}
 @Transactional public void addPrefix(UUID client,String value,String description){String p=value==null?"":value.trim().toUpperCase();if(!p.matches("[A-Z0-9][A-Z0-9_-]{1,29}"))throw new IllegalArgumentException("Invalid campaign prefix");try{jdbc.update("insert into campaign_prefix(client_id,prefix,normalized_prefix,description) values(?,?,?,?)",client,p,p,description);}catch(DataIntegrityViolationException e){throw new DataIntegrityViolationException("Active campaign prefix belongs to another client",e);}audit.record("PREFIX_CREATE","CampaignPrefix",null,"Campaign prefix created",null,Map.of("prefix",p));}
 public String validatePrefix(UUID client,String campaign){if(campaign==null||campaign.isBlank())return "CAMPAIGN_WITHOUT_PREFIX";String p=campaign.trim().split("\\s+",2)[0].toUpperCase();List<UUID> owners=jdbc.query("select client_id from campaign_prefix where normalized_prefix=? and active and valid_until is null",(rs,n)->rs.getObject(1,UUID.class),p);if(owners.isEmpty())return "UNKNOWN_PREFIX";return owners.getFirst().equals(client)?"CORRECT_PREFIX":"PREFIX_BELONGS_TO_OTHER_CLIENT";}
 private void requireId(String id){if(id==null||!id.trim().matches("[0-9]{3,80}"))throw new IllegalArgumentException("Meta IDs must contain digits and are stored as text");} private String normalize(String v){return Normalizer.normalize(v.trim().toLowerCase(),Normalizer.Form.NFD).replaceAll("\\p{M}","");}}
