package com.sodi.metareports.shared.web;
import com.sodi.metareports.metric.MetricsService;
import java.math.BigDecimal;
import java.time.LocalDate;
import com.sodi.metareports.branding.BrandingService; import com.sodi.metareports.client.*; import com.sodi.metareports.client.dto.ClientForm; import com.sodi.metareports.client.repository.ClientRepository; import com.sodi.metareports.incident.IncidentService; import com.sodi.metareports.metaaccount.AssetService; import com.sodi.metareports.role.repository.RoleRepository; import com.sodi.metareports.synchronization.SynchronizationService; import com.sodi.metareports.user.*; import com.sodi.metareports.user.dto.UserForm; import com.sodi.metareports.user.repository.AppUserRepository; import jakarta.validation.Valid; import java.util.UUID; import org.springframework.data.domain.PageRequest; import org.springframework.security.access.prepost.PreAuthorize; import org.springframework.stereotype.Controller; import org.springframework.ui.Model; import org.springframework.validation.BindingResult; import org.springframework.web.bind.annotation.*; import org.springframework.web.multipart.MultipartFile; import org.springframework.web.servlet.mvc.support.RedirectAttributes;
@Controller @RequestMapping("/admin") public class AdminController { private final AppUserRepository users; private final UserAdminService userService; private final RoleRepository roles; private final ClientRepository clients; private final ClientService clientService; private final AssetService assets; private final BrandingService branding; private final SynchronizationService synchronization; private final IncidentService incidents; private final MetricsService metrics;
 public AdminController(AppUserRepository u,UserAdminService us,RoleRepository r,ClientRepository c,ClientService cs,AssetService a,BrandingService b,SynchronizationService s,IncidentService i,MetricsService m){users=u;userService=us;roles=r;clients=c;clientService=cs;assets=a;branding=b;synchronization=s;incidents=i;metrics=m;}
 @GetMapping public String dashboard(Model m){m.addAttribute("users",users.count());m.addAttribute("clients",clients.count());m.addAttribute("assets",assets.count());return "admin/dashboard";}
 @GetMapping("/assets") @PreAuthorize("hasAuthority('META_ASSET_VIEW')") public String assets(Model m){m.addAttribute("assets",assets.all());return "admin/assets/list";}
 @GetMapping("/synchronizations") @PreAuthorize("hasAuthority('META_ASSET_VIEW')") public String synchronizations(Model m){m.addAttribute("executions",synchronization.executions());return "admin/synchronizations/list";}
 @PostMapping("/synchronizations") @PreAuthorize("hasAuthority('SYNC_EXECUTE')") public String runSynchronization(@RequestParam(defaultValue="phase3-demo") String fixture,RedirectAttributes r){try{UUID id=synchronization.runFixture(fixture);r.addFlashAttribute("success","Sincronización completada: "+id);}catch(RuntimeException e){r.addFlashAttribute("error",e.getMessage());}return "redirect:/admin/synchronizations";}
 @GetMapping("/incidents") @PreAuthorize("hasAuthority('INCIDENT_VIEW')") public String incidents(Model m){m.addAttribute("incidents",incidents.all());m.addAttribute("clients",incidents.activeClients());return "admin/incidents/list";}
 @PostMapping("/incidents/{id}/resolve") @PreAuthorize("hasAuthority('INCIDENT_RESOLVE')") public String resolveIncident(@PathVariable UUID id,@RequestParam UUID clientId,@RequestParam String note,RedirectAttributes r){return incidentAction(()->incidents.resolve(id,clientId,note),"Incidencia resuelta",r);}
 @PostMapping("/incidents/{id}/ignore") @PreAuthorize("hasAuthority('INCIDENT_RESOLVE')") public String ignoreIncident(@PathVariable UUID id,@RequestParam String note,RedirectAttributes r){return incidentAction(()->incidents.ignore(id,note),"Incidencia ignorada",r);}
 @PostMapping("/incidents/{id}/reprocess") @PreAuthorize("hasAuthority('INCIDENT_RESOLVE')") public String reprocessIncident(@PathVariable UUID id,@RequestParam String note,RedirectAttributes r){return incidentAction(()->incidents.reprocess(id,note),"Incidencia reprocesada",r);}
 @GetMapping("/metrics") @PreAuthorize("hasAuthority('REPORT_VIEW')") public String metrics(Model m){m.addAttribute("periods",metrics.periods());m.addAttribute("rates",metrics.rates());m.addAttribute("clients",metrics.clients());return "admin/metrics/list";}
 @PostMapping("/metrics/import") @PreAuthorize("hasAuthority('SYNC_EXECUTE')") public String importMetrics(RedirectAttributes r){return metricsAction(()->r.addFlashAttribute("success","Métricas importadas: "+metrics.importFixture()),r);}
 @PostMapping("/metrics/rates") @PreAuthorize("hasAuthority('REPORT_GENERATE')") public String rate(@RequestParam LocalDate month,@RequestParam String source,@RequestParam String target,@RequestParam BigDecimal rate,@RequestParam String rateSource,RedirectAttributes r){return metricsAction(()->{metrics.saveRate(month,source,target,rate,rateSource);r.addFlashAttribute("success","Tasa guardada");},r);}
 @PostMapping("/metrics/periods") @PreAuthorize("hasAuthority('REPORT_GENERATE')") public String period(@RequestParam UUID clientId,@RequestParam LocalDate start,@RequestParam LocalDate end,RedirectAttributes r){return metricsAction(()->{UUID id=metrics.createPeriod(clientId,start,end);r.addFlashAttribute("success","Período creado: "+id);},r);}
 @GetMapping("/reports/{id}/review") @PreAuthorize("hasAuthority('REPORT_VIEW')") public String review(@PathVariable UUID id,Model m){m.addAttribute("period",metrics.period(id));m.addAttribute("rows",metrics.review(id));return "admin/reports/review";}
 @GetMapping("/users") @PreAuthorize("hasAuthority('USER_VIEW')") public String users(Model m){m.addAttribute("users",users.findAll());return "admin/users/list";}
 @GetMapping("/users/new") @PreAuthorize("hasAuthority('USER_CREATE')") public String userForm(Model m){m.addAttribute("userForm",new UserForm());m.addAttribute("roles",roles.findAll());return "admin/users/form";}
 @PostMapping("/users") @PreAuthorize("hasAuthority('USER_CREATE')") public String createUser(@Valid @ModelAttribute UserForm userForm,BindingResult b,Model m,RedirectAttributes r){if(b.hasErrors()){m.addAttribute("roles",roles.findAll());return "admin/users/form";}try{userService.create(userForm);r.addFlashAttribute("success","Usuario creado");return "redirect:/admin/users";}catch(RuntimeException e){b.reject("user",e.getMessage());m.addAttribute("roles",roles.findAll());return "admin/users/form";}}
 @PostMapping("/users/{id}/toggle") @PreAuthorize("hasAuthority('USER_DISABLE')") public String toggleUser(@PathVariable UUID id){userService.toggle(id);return "redirect:/admin/users";}
 @PostMapping("/users/{id}/unlock") @PreAuthorize("hasAuthority('USER_UPDATE')") public String unlock(@PathVariable UUID id){userService.unlock(id);return "redirect:/admin/users";}
 @PostMapping("/users/{id}/password") @PreAuthorize("hasAuthority('USER_UPDATE')") public String password(@PathVariable UUID id,@RequestParam String password,RedirectAttributes r){userService.password(id,password);r.addFlashAttribute("success","Contraseña actualizada");return "redirect:/admin/users";}
 @GetMapping("/clients") @PreAuthorize("hasAuthority('CLIENT_VIEW')") public String clients(@RequestParam(defaultValue="0") int page,Model m){m.addAttribute("clients",clients.findAllByOrderByCommercialNameAsc(PageRequest.of(Math.max(0,page),20)));return "admin/clients/list";}
 @GetMapping("/clients/new") @PreAuthorize("hasAuthority('CLIENT_CREATE')") public String clientForm(Model m){m.addAttribute("clientForm",new ClientForm());return "admin/clients/form";}
 @PostMapping("/clients") @PreAuthorize("hasAuthority('CLIENT_CREATE')") public String createClient(@Valid @ModelAttribute ClientForm clientForm,BindingResult b,RedirectAttributes r){if(b.hasErrors())return "admin/clients/form";try{var c=clientService.create(clientForm);r.addFlashAttribute("success","Cliente creado");return "redirect:/admin/clients/"+c.getId();}catch(RuntimeException e){b.reject("client",e.getMessage());return "admin/clients/form";}}
 @GetMapping("/clients/{id}") @PreAuthorize("hasAuthority('CLIENT_VIEW')") public String client(@PathVariable UUID id,Model m){m.addAttribute("client",clientService.get(id));m.addAttribute("assets",assets.forClient(id));m.addAttribute("prefixes",assets.prefixes(id));m.addAttribute("branding",branding.find(id));return "admin/clients/detail";}
 @PostMapping("/clients/{id}/toggle") @PreAuthorize("hasAuthority('CLIENT_DISABLE')") public String toggleClient(@PathVariable UUID id){clientService.toggle(id);return "redirect:/admin/clients/"+id;}
 @PostMapping("/clients/{id}/facebook") @PreAuthorize("hasAuthority('META_ASSET_CREATE')") public String facebook(@PathVariable UUID id,@RequestParam String metaId,@RequestParam String name,RedirectAttributes r){return assetAction(()->assets.addFacebook(id,metaId,name),id,r);}
 @PostMapping("/clients/{id}/instagram") @PreAuthorize("hasAuthority('META_ASSET_CREATE')") public String instagram(@PathVariable UUID id,@RequestParam String metaId,@RequestParam String username,RedirectAttributes r){return assetAction(()->assets.addInstagram(id,metaId,username),id,r);}
 @PostMapping("/clients/{id}/ad-account") @PreAuthorize("hasAuthority('META_ASSET_CREATE')") public String adAccount(@PathVariable UUID id,@RequestParam String metaId,@RequestParam String name,@RequestParam String currency,@RequestParam(defaultValue="false") boolean exclusive,RedirectAttributes r){return assetAction(()->assets.addAdAccount(id,metaId,name,currency,exclusive),id,r);}
 @PostMapping("/clients/{id}/prefix") @PreAuthorize("hasAuthority('META_ASSET_CREATE')") public String prefix(@PathVariable UUID id,@RequestParam String prefix,@RequestParam(defaultValue="") String description,RedirectAttributes r){return assetAction(()->assets.addPrefix(id,prefix,description),id,r);}
 @PostMapping("/clients/{id}/branding") @PreAuthorize("hasAuthority('CLIENT_UPDATE')") public String branding(@PathVariable UUID id,@RequestParam(defaultValue="") String primaryColor,@RequestParam(defaultValue="") String secondaryColor,@RequestParam(defaultValue="") String accentColor,@RequestParam(defaultValue="") String header,@RequestParam(defaultValue="") String footer,@RequestParam(required=false) MultipartFile logo,RedirectAttributes r){return assetAction(()->branding.update(id,primaryColor,secondaryColor,accentColor,header,footer,logo),id,r);}
 private String assetAction(Runnable action,UUID id,RedirectAttributes r){try{action.run();r.addFlashAttribute("success","Registro guardado");}catch(RuntimeException e){r.addFlashAttribute("error",e.getMessage());}return "redirect:/admin/clients/"+id;}
 private String incidentAction(Runnable action,String success,RedirectAttributes r){try{action.run();r.addFlashAttribute("success",success);}catch(RuntimeException e){r.addFlashAttribute("error",e.getMessage());}return "redirect:/admin/incidents";}
 private String metricsAction(Runnable action,RedirectAttributes r){try{action.run();}catch(RuntimeException e){r.addFlashAttribute("error",e.getMessage());}return "redirect:/admin/metrics";}}
